service: hope-triggers

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1

functions:
  postAuth:
    handler: handler.postAuth
