/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

window.awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:901b12f7-7d89-4cbb-a761-2771fea433c3",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_7klGtD061",
    "aws_user_pools_web_client_id": "2og5v1n2p98jc7eu2fg8qi38ml",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


// export default awsmobile;
